# Generated by Django 3.2.3 on 2021-06-10 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_blog_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
