# Generated by Django 3.2.6 on 2021-08-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_alter_blog_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='liked',
        ),
    ]
