# Generated by Django 3.2.6 on 2021-09-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_remove_blog_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
            ],
        ),
    ]
