# Generated by Django 3.2.6 on 2021-09-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_link',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
