# Generated by Django 3.2.6 on 2022-07-13 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_news_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ipadd',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
